import './JS/autorisation';
import './JS/home-by-category';
import './JS/header';
import './JS/PopUp/modalPopUp';
import './JS/categories';
import './JS/scroll-up';
import './JS/modal-single-book';
import './JS/support';
import './JS/scroll-up';
import './JS/colorTheme';
import './JS/BestSellers/bestSellers';
import './JS/loader';
import './JS/modal-start';
import './JS/Auth/app'